import type { Task } from "./types";

const now = new Date().toISOString();

export const SEED_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Set up project repository",
    description: "Initialize the monorepo with Next.js, Tailwind, and Shadcn UI",
    status: "DONE",
    assignee: "Alice",
    createdAt: now,
    updatedAt: now,
    dueDate: null,
    parentId: null,
  },
  {
    id: "task-2",
    title: "Design database schema",
    description: "Define tables for users and tasks with all constraints",
    status: "IN_REVIEW",
    assignee: "Bob",
    createdAt: now,
    updatedAt: now,
    dueDate: null,
    parentId: null,
  },
  {
    id: "task-3",
    title: "Implement authentication API",
    description: "Build register, login, and logout endpoints",
    status: "IN_PROGRESS",
    assignee: "Alice",
    createdAt: now,
    updatedAt: now,
    dueDate: "2026-03-25",
    parentId: null,
  },
  {
    id: "task-3a",
    title: "Registration endpoint",
    description: "Build POST /api/auth/register",
    status: "DONE",
    assignee: "Alice",
    createdAt: now,
    updatedAt: now,
    dueDate: null,
    parentId: "task-3",
  },
  {
    id: "task-3b",
    title: "Login endpoint",
    description: "Build POST /api/auth/login",
    status: "IN_PROGRESS",
    assignee: "Alice",
    createdAt: now,
    updatedAt: now,
    dueDate: null,
    parentId: "task-3",
  },
  {
    id: "task-3c",
    title: "Logout endpoint",
    description: "Build POST /api/auth/logout",
    status: "TODO",
    assignee: "Alice",
    createdAt: now,
    updatedAt: now,
    dueDate: null,
    parentId: "task-3",
  },
  {
    id: "task-4",
    title: "Build task CRUD API",
    description: "Create, read, update, delete endpoints for tasks",
    status: "TODO",
    assignee: "Robert",
    createdAt: now,
    updatedAt: now,
    dueDate: "2026-03-28",
    parentId: null,
  },
  {
    id: "task-5",
    title: "Create task list UI",
    description: "Main view with filters and search",
    status: "TODO",
    assignee: "Bob",
    createdAt: now,
    updatedAt: now,
    dueDate: "2026-04-01",
    parentId: null,
  },
  {
    id: "task-6",
    title: "Write API integration tests",
    description: "Test all auth and task endpoints",
    status: "TODO",
    assignee: null,
    createdAt: now,
    updatedAt: now,
    dueDate: null,
    parentId: null,
  },
];
